name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: ./amper test
      - name: Generate Kover Report
        run: ./gradlew koverXmlReport
      - uses: actions/upload-artifact@v4
        name: Upload Kover Report
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: build/reports/json-query-kt/jvm/TEST-junit-jupiter.xml

